# Generated by Django 4.0 on 2021-12-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_model.category'),
        ),
    ]
