# Generated by Django 4.0 on 2021-12-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_model', '0002_alter_category_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parentID',
            new_name='parent',
        ),
    ]
