# Generated by Django 4.0 on 2021-12-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_model', '0003_rename_parentid_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
