# Generated by Django 4.0 on 2021-12-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_model', '0005_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
