# Generated by Django 4.0 on 2021-12-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_model', '0006_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
