# Generated by Django 4.0 on 2021-12-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_model', '0008_rename_parent_category_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
